// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace M000_DataAccess.Models;

[Table("Kurse")]
public partial class Kurse
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

	[StringLength(100, MinimumLength = 5, ErrorMessage = "Der Kursname muss zw. 5 und 100 Zeichen haben!")] //ErrorMessageResourceName: Lokalisierung von Fehlermeldungen
	[Unicode(false)]
    public string Kursname { get; set; }

    public int? DauerInTagen { get; set; }

    public byte? Aktiv { get; set; }

    [InverseProperty("Kurs")]
    public virtual ICollection<KursInhalte> KursInhaltes { get; set; } = new List<KursInhalte>();
}